### ISSUE TITLE
Cannot create a module for angular-bootstrap

### ISSUE THREAD

**Issue by joshkurz** [jimrhoskins/ngmodules.org#2]
The app will not let me create a module for https://github.com/angular-ui/bootstrap as the url. Maybe I am doing something wrong. The error says the Github repo is invalid.

**Comment by jimrhoskins** [comment]
I tried it out and it worked. The field is intended for the "username/repo" portion of the github url. Maybe the prepended github.com/ in front of the input isn't obvious. 

Did you by any chance place the full url in that field (http:// and all)? 

I think I will write some better error messages, and add some js to strip the repo down to the desired portion

**Comment by joshkurz** [comment]
yeah I did actually put the whole url in. Thanks. I really like the direction this app is going.

**Comment by jimrhoskins** [comment]
I deployed some javascript to reformat the url if you paste the full url. That should reduce confusion.

Thanks for reporting it!

**Comment by lavinjj** [comment]
Sorry, but it is still happening. I just tried to add a module. I entered lavinjj/LocalizationService, clicked on the big blue button to get the info from GitHub, which it did perfectly. I added a couple of tags and some text in the explanation and I got the message Github repo is invalid.

So you might want to take a look at it.

**Comment by jimrhoskins** [comment]
@lavinjj Thanks, I did have an error, as my validation was only taking all-lowercase repo names. I updated the code and deployed and was able to create lavinjj/LocalizationService. I then removed it so you can add it with appropriate info.

Thanks for submitting your module and this bug report!

**Comment by joshkurz** [comment]
Im gonna reopen this for now. If its fixed @jimrhoskins then go ahead and close it. 

Thanks

**Comment by lavinjj** [comment]
@jimrhoskins, that worked. I was able to add the module. But it seems that your removal of the test module did not work. I kept getting an error that the module name existed, so I gave it a different name. 

Thanks.

**Comment by jimrhoskins** [comment]
Whoops, yes, I realized last night that the remove links weren't working and pushed a fix. I must have gotten distracted and not successfully deleted my test. I have now, and I took the liberty of renaming your module back (but if you want to change it, go ahead)

Incidentally, since the github repo was under your name, you should have been able to edit it even though I submitted it.

Anyway, your submitted module with it's original name is here http://ngmodules.org/modules/LocalizationService

I'm going to close this since I believe the fixes related to github naming should be fixed for now
